openid_auth/urls.py
# -*- coding: utf-8 -*-
# Copyright 2007, 2008,2009 by Benoît Chesneau <benoitc@e-engura.org>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView

# views
from django.contrib.auth import views as auth_views
from django.conf import settings
from openid_auth import views as oid_views
from registration import views as reg_views
from registration.views import activate
from registration.views import register
from registration_backend.forms import MadronaRegistrationForm

urlpatterns = patterns('',
    url(r'^password/reset/$', auth_views.password_reset, name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='auth_password_reset_done'),
    url(r'^password/$',oid_views.password_change, name='auth_password_change'),

    # manage account registration
    url(r'^associate/complete/$', oid_views.complete_associate, name='user_complete_associate'),
    url(r'^associate/$', oid_views.associate, name='user_associate'),
    url(r'^dissociate/$', oid_views.dissociate, name='user_dissociate'),
    url(r'^register/$', oid_views.register, name='user_register'),
    url(r'^signout/$', oid_views.signout, {'next_page':  settings.LOGIN_REDIRECT_URL}, name='user_signout'),
    url(r'^signout/$', oid_views.signout, {'next_page': settings.LOGIN_REDIRECT_URL}, name='auth_logout'),
    url(r'^signin/complete/$', oid_views.complete_signin, name='user_complete_signin'),
    url(
        r'^signup/$',
        reg_views.register,
        {'backend': 'registration.backends.default.DefaultBackend', 
         'form_class': MadronaRegistrationForm},
        name='registration_register'
    ),
    url(r'^signup/complete/$',
        TemplateView.as_view(template_name='registration/registration_complete.html'),
        name='registration_complete'),

    url(r'^activate/complete/$',
        TemplateView.as_view(template_name='registration/activation_complete.html'),
        {'extra_context': {'group_request_email': settings.GROUP_REQUEST_EMAIL}},
        name='registration_activation_complete'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$',
        activate,
        {'backend': 'madrona.common.registration_backend.LingcodBackend'},
        name='registration_activate'),
    url(r'^register/closed/$',
        TemplateView.as_view(template_name='registration/registration_closed.html'),
        name='registration_disallowed'),

    # yadis uri
    url(r'^yadis.xrdf$', oid_views.xrdf, name='oid_xrdf'),
)


## The openid login behavior can be 'hidden' by use of a 
# template which only allows local user/pass authentication
# Note that this does not disable openid completely; user could still
# POST openid credentials if they wanted to
try:
    use_openid = settings.OPENID_ENABLED
except:
    use_openid = False

if use_openid:
    template_name = 'authopenid/signin.html'
else:
    template_name = 'authopenid/signin_local.html'

urlpatterns += patterns('',
    url(r'^signin/$', oid_views.signin, {'template_name':template_name}, name='user_signin'),
    url(r'^signin/$', oid_views.signin, {'template_name':template_name}, name='auth_login'),
)

openid_auth/forms.py
# -*- coding: utf-8 -*-
# Copyright 2007, 2008,2009 by Benoît Chesneau <benoitc@e-engura.org>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import re

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.utils.translation import ugettext as _
from django.conf import settings
# needed for some linux distributions like debian
try:
    from openid.yadis import xri
except ImportError:
    from yadis import xri

from openid_auth.models import UserAssociation


class OpenidSigninForm(forms.Form):
    """ signin form """
    openid_url = forms.CharField(max_length=255, 
            widget=forms.widgets.TextInput(attrs={'class': 'required openid'}))

    def clean_openid_url(self):
        """ test if openid is accepted """
        if 'openid_url' in self.cleaned_data:
            openid_url = self.cleaned_data['openid_url']
            if xri.identifierScheme(openid_url) == 'XRI' and getattr(
                settings, 'OPENID_DISALLOW_INAMES', False
                ):
                raise forms.ValidationError(_('i-names are not supported'))
            return self.cleaned_data['openid_url']

attrs_dict = {'class': 'required login'}
username_re = re.compile(r'^\w+$')

class OpenidRegisterForm(forms.Form):
    """ openid signin form """
    username = forms.CharField(max_length=30, 
            widget=forms.widgets.TextInput(attrs=attrs_dict))
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict, 
        maxlength=200)), label=u'Email address')

    def __init__(self, *args, **kwargs):
        super(OpenidRegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def clean_username(self):
        """ test if username is valid and exist in database """
        if 'username' in self.cleaned_data:
            if not username_re.search(self.cleaned_data['username']):
                raise forms.ValidationError(_("Usernames can only contain \
                    letters, numbers and underscores"))
            try:
                user = User.objects.get(
                        username__exact=self.cleaned_data['username']
                )
            except User.DoesNotExist:
                return self.cleaned_data['username']
            except User.MultipleObjectsReturned:
                raise forms.ValidationError(u'There is already more than one \
                    account registered with that username. Please try \
                    another.')
            self.user = user
            raise forms.ValidationError(_("This username is already \
                taken. Please choose another."))

    def clean_email(self):
        """For security reason one unique email in database"""
        if 'email' in self.cleaned_data:
            try:
                user = User.objects.get(email=self.cleaned_data['email'])
            except User.DoesNotExist:
                return self.cleaned_data['email']
            except User.MultipleObjectsReturned:
                raise forms.ValidationError(u'There is already more than one \
                    account registered with that e-mail address. Please try \
                    another.')
            raise forms.ValidationError(_("This email is already \
                registered in our database. Please choose another."))


class AssociateOpenID(forms.Form):
    """ new openid association form """
    openid_url = forms.CharField(max_length=255, 
            widget=forms.widgets.TextInput(attrs={'class': 'required openid'}))

    def __init__(self, user, *args, **kwargs):
        super(AssociateOpenID, self).__init__(*args, **kwargs)
        self.user = user

    def clean_openid_url(self):
        """ test if openid is accepted """
        if 'openid_url' in self.cleaned_data:
            openid_url = self.cleaned_data['openid_url']
            if xri.identifierScheme(openid_url) == 'XRI' and getattr(
                settings, 'OPENID_DISALLOW_INAMES', False
                ):
                raise forms.ValidationError(_('i-names are not supported'))

            try:
                rel = UserAssociation.objects.get(openid_url__exact=openid_url)
            except UserAssociation.DoesNotExist:
                return self.cleaned_data['openid_url']

            if rel.user != self.user:
                raise forms.ValidationError(_("This openid is already \
                    registered in our database by another account. Please choose another."))

            raise forms.ValidationError(_("You already associated this openid to your account."))

class OpenidDissociateForm(OpenidSigninForm):
    """ form used to dissociate an openid. """
    openid_url = forms.CharField(max_length=255, widget=forms.widgets.HiddenInput())

openid_auth/templates/authopenid/associate.html
{% extends "authopenid/base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
{% if msg %}
	<div class="errors"><p>{{ msg }}</p></div>
{% endif %}

{% if form.errors %}
    <div class="errors"><p>Openid url : {{ form.openid_url.errors|join:', ' }}</p></div>
{% endif %}

<div class="login">

<form name="openid_form" id="openid_form" action="{% url 'user_associate' %}" method="post">
    <input type="hidden" name="action" value="verify" />
    <input type="hidden" name="next" value="{{ next }}" />
	<fieldset>
		<legend>{% trans "Add a new OpenID URL" %}</legend>
		<div id="openid_choice">
    		<p>Please click your account provider:</p>
    		<div id="openid_btns"></div>
    	</div>
    	<div id="openid_input_area">
            <label for="id_openid_url">{% trans "OpenId URL :" %}</label><br />{{ form.openid_url }}
            <input name="openid_submit" type="submit" value="{% trans "Add OpenID" %}">
		</div>
	</fieldset>
</form>	
</div>	
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}/js/openid-jquery.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    openid.init('id_openid_url');
});
</script>
{% endblock %}

openid_auth/templates/authopenid/base.html
{% load appname %}<!DOCTYPE html>
{% load url from future %}
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>{% appname %} Sign In</title>
        <!--[if IE]>

        <script>
            // allow IE to recognize HTMl5 elements
            document.createElement('section');
            document.createElement('article');
            document.createElement('aside');
            document.createElement('footer');
            document.createElement('header');
            document.createElement('nav');
            document.createElement('time');

        </script>
        <![endif]-->
        {% if request.is_secure %}
        <meta http-equiv="X-XRDS-Location" content="https://{{ request.get_host }}{% url 'oid_xrdf' %}" />
        {% else %}
        <meta http-equiv="X-XRDS-Location" content="http://{{ request.get_host }}{% url 'oid_xrdf' %}" />  
        {% endif %}

        <link rel="stylesheet" href="{{ MEDIA_URL }}/openid/css/openid.css" />
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block content %}{% endblock %}
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    	{% block extra_scripts %}{% endblock %}
    </body>
</html>

openid_auth/templates/authopenid/complete.html
{% extends "authopenid/base.html" %}
{% load i18n %}
{% load url from future %}

{% block head %}{% endblock %}

{% block content %}

	<div id="completetxt">
	<h2>{% trans "Your OpenID is verified! " %}</h2>

    <div>

      <div class="login">
          <p> 
          New to this site?
          <a href="{% url 'registration_register' %}">Register for a new local account</a>.
          </p>
      </div>

      <h3> OR </h3>

      <div class="login" style="width:400px;">
        <p> Associate with existing account </p>
        <form name="fverify" action="{% url 'user_register' %}" method="POST">
            <input type="hidden" name="next" value="{{ next }}" />
			<fieldset>
				<legend>{% trans "An existing account" %}</legend>
				<div class="form-row"><label for="id_username">{% trans "Username" %}</label><br />{{ form2.username }}</div>
				<div class="form-row"><label for="id_passwordl">{% trans "Password" %}</label><br />{{ form2.password }}</div>
				<div class="submit-row"><input type="submit" name="bverify" value="{% trans "Verify" %}"></div>
			</fieldset>
		</form>
	  </div>

    </div>	

	{% if form1.errors %}
	<p class="errors">{% trans "Please correct errors below:" %}<br />
		{% if form1.username.errors %} 
			<span class="error">{{ form1.username.errors|join:", " }}</span>
		{% endif %}
		{% if form1.email.errors %} 
			<span class="error">{{ form1.email.errors|join:", " }}</span>
		{% endif %}
	</p>
	{% endif %}
	{% if form2.errors %}
	<p class="errors">{% trans "Please correct errors below:" %}<br />
		{% if form2.username.errors %} 
			<span class="error">{{ form2.username.errors|join:", " }}</span>
		{% endif %}
		{% if form2.password.errors %} 
			<span class="error">{{ form2.password.errors|join:", " }}</span>
		{% endif %}
	</p>
	{% endif %}
    </div>


	
{% endblock %}

	

openid_auth/templates/authopenid/dissociate.html
{% extends "authopenid/base.html" %}
{% load i18n %}

{% block head %}


{% endblock %}


{% block content %}
{% if msg %}
	<p class="warning">{{ msg }}</p>
{% endif %}

<div class="login">

<form name="fopenid" action="" method="post">
    <input type="hidden" name="next" value="{{ next }}" />
	{{ form.openid_url }}
	<fieldset>
		<legend>{% trans "Dissociate OpenID URL" %}</legend>
        <p>Confirm to dissociate {{ openid_url }} from your account</p>
        <div class="submit-row "><input name="bdissociate" type="submit" value="{% trans "Dissociate OpenID" %}"></div>
		
	</fieldset>
</form>	
</div>	
{% endblock %}

openid_auth/templates/authopenid/failure.html
{% extends "authopenid/base.html" %}
{% load i18n %}

{% block head %}
{% endblock %}


{% block content %}
<h1>OpenID failed</h1>

<p>{{ message|escape }}</p>
{% endblock %}

openid_auth/templates/authopenid/password_change_form.html
{% extends "authopenid/base.html" %}
{% load i18n %}


{% block content %}




{% if set_password %}
<h1>{% trans 'Set password' %}</h1>
<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form action="" method="post">
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}</p>
<p><input type="submit" value="{% trans 'Change my password' %}" /></p>
</form>

{% else %}

<h1>{% trans 'Password change' %}</h1>
<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<form action="" method="post">

{{ form.old_password.errors }}
<p class="aligned wide"><label for="id_old_password">{% trans 'Old password:' %}</label>{{ form.old_password }}</p>
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}</p>

<p><input type="submit" value="{% trans 'Change my password' %}" /></p>
</form>



{% endif %}
{% endblock %} 

openid_auth/templates/authopenid/signin.html
{% extends "authopenid/base.html" %}
{% load i18n %}
{% load appname %}
{% load url from future %}

{% block content %}
{% if msg %}
<br />
	<p class="warning">{{ msg }}</p>
{% endif %}
{% if form2.errors %}
<div class="errors"><p>{% trans "Please correct errors below:" %}<br />
	{% if form2.username.errors %} 
		<span class="error">USERNAME errors {{ form2.username.errors|join:", " }}</span>
        <br/>
	{% endif %}
         
	{% if form2.password.errors %} 
		<span class="error">PASSWORD errors {{ form2.password.errors|join:", " }}</span>
        <br/>
	{% endif %}
</p></div>

{% endif %}

{% if form1.errors %}
<div class="errors">
    <p><span class="error">{{ form1.openid_url.errors|join:", " }}</span></p>
</div>
<br>
{% endif %}
<h2>Sign into {% appname %}</h2>
<!-- EVENTUALLY link to reg 
<p> <a href="{% url 'registration_register' %}">Register</a> | <a href="{% url 'user_signin' %}">Log-In</a></p> -->

<div class="login">

<form id="auth_form" name="auth_form" action="{% url 'user_signin' %}" method="post">
    <p class="explain">If you only have an account with this site and dont wish to use any other related sites, use this method. </p>

    <input type="hidden" name="next" value="{{ next }}" />
	<fieldset>
		<legend>{% trans "Sign In Using Your Account ID" %}</legend>
		<div class="form-row"><label for="id_username">{% trans "Username:" %}</label><br />{{ form2.username }}</div>
		<div class="form-row"><label for="id_password">{% trans "Password" %}</label><br />{{ form2.password }}</div>
        <div class="submit-row"><input type="submit" name="blogin" value="{% trans "Sign in" %}"> </div>
	</fieldset>	
</form>

<form id="openid_form" name="openid_form" action="{% url 'user_signin' %}" method="post">
    <p class="explain">If you have a third-part account, use this method to log into this site and all supported sites. </p>
    <input type="hidden" name="action" value="verify" />
    <input type="hidden" name="next" value="{{ next }}" />
	<fieldset>
		<legend>{% trans "Sign In Using Your OpenID URL" %}</legend>
		<div id="openid_choice">
    		<p>Please click your account provider:</p>
    		<div id="openid_btns"></div>
    	</div>
    	    <div id="openid_input_area">
                <label for="openid_url">OpenId URL :</label><input id="openid_url" type="text" class="required openid" name="openid_url" maxlength="255" />
                <input name="openid_submit" type="submit" value="{% trans "Sign in with OpenID" %}">
            </div>
		
	</fieldset>
</form>	

</div>	
{% endblock %}


{% block extra_scripts %}
<script type="text/javascript" src="{{MEDIA_URL}}/openid/js/openid-jquery.js"></script> 
<script type="text/javascript">
$(document).ready(function() {
    openid.img_path = '{{MEDIA_URL}}/openid/images/';
    openid.init('openid_url');
});
</script>
{% endblock %}

openid_auth/templates/authopenid/signin_local.html
{# extends "authopenid/base.html" #}
{% extends 'panel/panel.html' %}
{% load appname %}
{% load url from future %}
{% block title %}Sign In{% endblock title %}

{% block panel %}
{% if msg %}
<br />
	<p class="warning">{{ msg }}</p>
{% endif %}
{% if form2.errors %}
<div class="errors"><p>Please correct errors below:<br />
    {% if form2.non_field_errors %}
        <span class="error">{{ form2.non_field_errors }}</span>
        <br/>
    {% endif %}
	{% if form2.username.errors %} 
		<span class="error">USERNAME errors {{ form2.username.errors|join:", " }}</span>
        <br/>
	{% endif %}
	{% if form2.password.errors %} 
		<span class="error">PASSWORD errors {{ form2.password.errors|join:", " }}</span>
        <br/>
	{% endif %}
</p></div>

{% endif %}

{% if form1.errors %}
<div class="errors">
    <p><span class="error">{{ form1.openid_url.errors|join:", " }}</span></p>
</div>
<br>
{% endif %}

<div class="login" style="margin-top:25px">

<form id="auth_form" name="auth_form" action="{% url 'user_signin' %}" method="post">
    <input type="hidden" name="next" value="{{ next }}" />
	<fieldset>
        <legend><strong>Sign In To {% appname %}</strong></legend> 
		<div class="form-row"><label for="id_username">Username</label><br />{{ form2.username }}</div>
		<div class="form-row"><label for="id_password">Password</label><br />{{ form2.password }}</div>
        <div class="submit-row"><input type="submit" name="blogin" value="Sign in"> </div>
	</fieldset>	
</form>

<p><a class="panel_link" href="{% url 'auth_password_reset' %}">Forgot your password?</a></p>
</div>	
{% endblock panel %}